### ISSUE TITLE
Set a method to revert progress

### ISSUE THREAD

**Issue by AngleV** [lopspower/CircularFillableLoaders#10]
by now if you setprogress = 0 the wave covers up the whole view.
Would it be possible to add a method so that to revert the progress and setprogress = 0 wave start filling up the view ?

**Comment by nhjariwala** [comment]
@AngleV you can simply do that by subtracting your progress from 100.
For example:
set progress = 100 - yourValue;
In this case when you setup 0 wave start filling.

Hope that make sense

**Comment by lopspower** [comment]
Exacly @nhjariwala

**Comment by loudenvier** [comment]
I know this is a closed issue, but just by subtracting from 100 is not a perfect solution, since the wave is animated from "0" to 100... This creates distraction in the UI. It would be great to be able to control the progress by a property (that could be set as a layout parameter) so that the component behaved the same. It would also be semantically better than setting progress to 100 - percent.

To see what I mean, just add the loader, with a 90 percent set in the markup, to a blank activity. Every time the activity is shown, the circular fillable loader will animate from top to bottom, up to 90%. This may not be a serious issue in an activity, and could even be considered a conscious choice, but when used in a Recycler view, for, example, to show the upload progress of images (my current use case, actually) it gets in the way as the view will always animate from top to bottom whenever view holders are recycled and shown again.
